[package]
name = "swc4j"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
deno_ast = { version = "1.0.1", features = ["module_specifier", "transpiling", "transforms"] }
deno_media_type = "0.1.2"
jni = "0.21.1"
