[package]
name = "swc4j"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
jni = "0.21.1"
swc = "0.273.15"
