[package]
name = "swc4j"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
debug_print = "1.0.0"
deno_ast = { version = "0.36.1", features = [
  "bundler",
  "cjs",
  "codegen",
  "compat",
  "dep_analysis",
  "emit",
  "proposal",
  "react",
  "scopes",
  "sourcemap",
  "transforms",
  "transpiling",
  "typescript",
  "utils",
  "view",
  "visit",
] }
jni = "0.21.1"
num-bigint = "0.4.4"
