name: swc4j Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"

env:
  SWC4J_VERSION: 1.0.0

jobs:
  build_cross_platform:
    strategy:
      matrix:
        include:
          - image: ubuntu-latest
            os: android 
            arch: arm64
            ext: .so
            channel: stable
            target: aarch64-linux-android

    name: Build swc4j for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.image }}

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Installing Rust ${{ matrix.channel }} w/ ${{ matrix.target }}
      uses: dtolnay/rust-toolchain@master
      with:
        target: ${{ matrix.target }}
        toolchain: ${{ matrix.channel }}

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - name: Cargo Build and Test
      env:
        RUSTFLAGS: -Awarnings
      run: |
        cd rust
        cargo build -r --target ${{ matrix.target }}
        deno run --allow-all ../scripts/ts/copy_swc4j_lib.ts -o ${{ matrix.os }} -a ${{ matrix.arch }}

    - name: Setup JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 8

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.5

    - name: Build and Test
      run: |
        gradle build generatePomFileForGeneratePomPublication -x test --debug

    - name: Upload the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: swc4j-${{ matrix.os }}-${{ matrix.arch }}-${{ env.SWC4J_VERSION }}
        path: |
          build/libs/swc4j-${{ env.SWC4J_VERSION }}.jar
          build/libs/swc4j-${{ env.SWC4J_VERSION }}.pom
