name: swc4j Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"

env:
  SWC4J_VERSION: 1.0.0

jobs:
  build_cross_platform:
    strategy:
      matrix:
        include:
          - image: ubuntu-latest
            os: android 
            arch: arm64
            ndk-arch: aarch64
            ext: .so
            channel: stable
            target: aarch64-linux-android

    name: Build swc4j for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.image }}

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27
        local-cache: false

    # - name: Installing Rust ${{ matrix.channel }} w/ ${{ matrix.target }}
    #   uses: dtolnay/rust-toolchain@master
    #   with:
    #     target: ${{ matrix.target }}
    #     toolchain: ${{ matrix.channel }}

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - name: Cargo Build and Test
      env:
        RUSTFLAGS: -Awarnings
      run: |
        cd rust
        brew uninstall rust
        # sudo apt-get install binutils
        rustup target add ${{ matrix.target }}
        export CC=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.target }}24-clang
        export CXX=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.target }}24-clang++
        export AR=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
        export RUSTFLAGS="-L ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/lib/linux/${{ matrix.ndk-arch }} -L ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/${{ matrix.target }}/24 -C target-feature=+crt-static"
        # cargo build --release --target ${{ matrix.target }} --config target.${{ matrix.target }}.linker="'${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.target }}24-clang'"
        cargo rustc --crate-type cdylib build -r --target ${{ matrix.target }}
        deno run --allow-all ../scripts/ts/copy_swc4j_lib.ts -o ${{ matrix.os }} -a ${{ matrix.arch }}

    - name: Setup JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 8

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.5

    - name: Build and Test
      run: |
        gradle build generatePomFileForGeneratePomPublication -x test --debug

    - name: Upload the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: swc4j-${{ matrix.os }}-${{ matrix.arch }}-${{ env.SWC4J_VERSION }}
        path: |
          build/libs/swc4j-${{ env.SWC4J_VERSION }}.jar
          build/libs/swc4j-${{ env.SWC4J_VERSION }}.pom
